# Generated by Django 5.2 on 2026-06-11 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_weightentry_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weightentry",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "weight entry",
                "verbose_name_plural": "weight entries",
            },
        ),
        migrations.AlterField(
            model_name="weightentry",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="date and time of the weight measurement.",
            ),
        ),
        migrations.AlterField(
            model_name="weightentry",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="enter your weight in kilograms",
                max_digits=5,
            ),
        ),
    ]
