# Generated by Django 5.2 on 2026-06-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_weightentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', help_text='unit of the weight measurement (kg or lb)', max_length=2),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='enter your weight', max_digits=5),
        ),
    ]
