# Generated by Django 5.2 on 2026-06-26 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_weightentry_unit_alter_weightentry_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.DecimalField(decimal_places=2, default=75.0, help_text='enter your target weight in kg', max_digits=5)),
                ('preferred_unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', help_text='preferred display unit', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user settings',
                'verbose_name_plural': 'user settings',
            },
        ),
    ]
