# Generated by Django 5.2 on 2026-06-26 00:42

from django.db import migrations


def create_user_settings(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = apps.get_model('auth', 'User')
    UserSettings = apps.get_model('tracker', 'UserSettings')
    for user in User.objects.all():
        UserSettings.objects.get_or_create(user=user)


def delete_user_settings(apps, schema_editor):
    UserSettings = apps.get_model('tracker', 'UserSettings')
    UserSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_usersettings'),
    ]

    operations = [
        migrations.RunPython(create_user_settings, delete_user_settings),
    ]

