# Generated by Django 5.2

from django.db import migrations

def delete_google_social_apps(apps, schema_editor):
    try:
        SocialApp = apps.get_model('socialaccount', 'SocialApp')
        # Delete any Google SocialApp entries in the database to prevent conflicts
        # with settings-based configuration (SOCIALACCOUNT_PROVIDERS['google']['APP'])
        SocialApp.objects.filter(provider='google').delete()
    except LookupError:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20260626_0612'),
        ('socialaccount', '__first__'),
    ]

    operations = [
        migrations.RunPython(delete_google_social_apps, migrations.RunPython.noop),
    ]
